name: Deploy
inputs:
  environ:
    required: true
  port:
    required: true
  repo:
    required: false
    default: 'https://github.com/m4dr1nch/DPI741-python-greetings'
runs:
  using: "composite"

  steps:
    - name: Print title
      run: echo Deploying to ${{ inputs.environ }}
      shell: bash
    
    - name: Remove the app if running
      run: pm2 delete greetings-app-${{ inputs.environ }} || true
      shell: bash

    - name: Clone repository
      run: git clone $APP_REPO $APP_ENV
      shell: bash
      env:
        APP_ENV: ${{ inputs.environ }}
        APP_REPO: ${{ inputs.repo }}

    - name: Start app
      working-directory: ${{ inputs.environ }}
      shell: bash
      run: pm2 start app.py --name greetings-app-$APP_ENV -- --port $APP_PORT
      env:
        APP_ENV: ${{ inputs.environ }}
        APP_PORT: ${{ inputs.port }}
