name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install PIP Dependencies
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Print title
        run: echo Installing pip dependencies

      - name: Clone repository
        run: git clone https://github.com/m4dr1nch/DPI741-python-greetings app

      - name: Install pip dependencies
        run: pip install -r app/requirements.txt


  deploy-to-dev:
    needs: install-pip-deps
    name: Deploy on dev
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          environ: 'dev'
          repo: 'https://github.com/m4dr1nch/DPI741-python-greetings'
          port: 7001

  test-on-dev:
    needs: deploy-to-dev
    name: Test on dev
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          environ: 'dev'


  deploy-to-staging:
    needs: install-pip-deps
    name: Deploy on staging
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          environ: 'staging'
          repo: 'https://github.com/m4dr1nch/DPI741-python-greetings'
          port: 7001

  test-on-staging:
    needs: deploy-to-staging
    name: Test on staging
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          environ: 'staging'

  deploy-to-preprod:
    needs: install-pip-deps
    name: Deploy on preprod
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          environ: 'preprod'
          repo: 'https://github.com/m4dr1nch/DPI741-python-greetings'
          port: 7001

  test-on-preprod:
    needs: deploy-to-preprod
    name: Test on preprod
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          environ: 'preprod'

  deploy-to-prod:
    needs: install-pip-deps
    name: Deploy on prod
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          environ: 'prod'
          repo: 'https://github.com/m4dr1nch/DPI741-python-greetings'
          port: 7001

  test-on-prod:
    needs: deploy-to-prod
    name: Test on prod
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/test
        with:
          environ: 'preprod'
