name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install PIP Dependencies
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Print title
        run: echo Installing pip dependencies

      - name: Clone repository
        run: git clone https://github.com/m4dr1nch/DPI741-python-greetings app

      - name: Install pip dependencies
        run: pip install -r app/requirements.txt


  deploy-to-dev:
    needs: install-pip-deps
    name: Deploy on Dev
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Print title
        run: echo Deploying to DEV
      
      - name: Remove the app if running
        run: pm2 delete greetings-app-dev || true

      - name: Clone repository
        run: git clone https://github.com/m4dr1nch/DPI741-python-greetings app

      - name: Start app
        working-directory: app
        run: pm2 start app.py --name greetings-app-dev -- --port 7001


  test-on-dev:
    needs: deploy-to-dev
    name: Test on Dev
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Print title
        run: echo Testing on DEV

      - name: Get mocha
        run: git clone https://github.com/mtararujs/course-js-api-framework mocha

      - name: Install npm dependencies
        working-directory: mocha
        run: npm install

      - name: Run tests
        working-directory: mocha
        run: npm run greetings greetings_dev

#  deploy-to-staging:
#    name: Deploy to Staging
#    runs-on: self-hosted
#
#    steps:
#      - name: Deploy to Staging
#        run: echo test
#
#  test-on-staging:
#    name: Test on Staging
#    runs-on: self-hosted
#
#    steps:
#      - name: Test on Staging
#        run: echo test
#
#  deploy-to-preprod:
#    name: Deploy to Pre-prod
#    runs-on: self-hosted
#
#    steps:
#      - name: Deploy to Pre-prod
#        run: echo test
#
#  test-on-preprod:
#    name: Test on Pre-prod
#    runs-on: self-hosted
#
#    steps:
#      - name: Test on Pre-prod
#        run: echo test
#
#  deploy-to-prod:
#    name: Deploy to Prod
#    runs-on: self-hosted
#
#    steps:
#      - name: Deploy to Prod
#        run: echo test
#
#  test-on-prod:
#    name: Test on Prod
#    runs-on: self-hosted
#
#    steps:
#      - name: Test on Prod
#        run: echo test
